### ISSUE TITLE
math_anal 09_26 lemma_14

### ISSUE THREAD

**Issue by zimch** [zimch/abstracts#47]
change `\par $\Rightarrow M_{\delta_\epsilon}(x) - m_{\delta_\epsilon}(x) \le \epsilon$` to `\par $\Rightarrow M_{\delta_\epsilon}(x) - m_{\delta_\epsilon}(x) \le 2 \epsilon$` line 219

_verified source_

**Comment by lindy2076** [comment]
fixed by pull #54
